### PR TITLE
removed duplicate blog posts

### PR DESCRIPTION
**Pull request by l8l**

### CODE REVIEW

**Comment by janosh** [comment]
Thanks! How about we handle all queries in one go? At least the query for blog tags and the one for chapters also needs a locale filter.

**Comment by l8l** [comment]
Okay, sure, feel free to change that. I do not know how to insert a filter before a query (except when implementing it in a query that filters all assets but this seems to be less clear code) which is why I just inserted it in both queries.

**Comment by janosh** [comment]
Yes, adding a filter to each query individually is exactly how to do it. There's no way to apply a filter to all queries at once.

**Comment by l8l** [comment]
Ah okay, now I understand that you just want me to add the filter also to the standorte.js page. There is already a filter in place in that file as you can see here: https://github.com/StudentenBildenSchueler/sbs-homepage/blob/master/src/pages/standorte.js. 
I think we should thus first go ahead merging this PR to resolve the issue with the blog posts and later I will provide another one that takes care of the language selection in the anmeldung.

**Comment by janosh** [comment]
Oops, I forgot about that. Sorry for the noise. I'll merge now.

**Pull request merged**
